// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAM8CvO2epKef6AMzIjnuFCfRnHg0JrGk',
    appId: '1:946141681323:web:74a4ddb2cb31aafa7a09ee',
    messagingSenderId: '946141681323',
    projectId: 'flutterfirebasetemplatesapps',
    authDomain: 'flutterfirebasetemplatesapps.firebaseapp.com',
    storageBucket: 'flutterfirebasetemplatesapps.appspot.com',
    measurementId: 'G-EGSCWF58LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASv36VFHBo3EetXUg3Gc0dEzYrdD5LnLw',
    appId: '1:946141681323:android:56ba225e1241a5467a09ee',
    messagingSenderId: '946141681323',
    projectId: 'flutterfirebasetemplatesapps',
    storageBucket: 'flutterfirebasetemplatesapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNt4nwJX7NQHjnCcH-2cIybRM3VNzgKDY',
    appId: '1:946141681323:ios:3a5e20c8f87d455e7a09ee',
    messagingSenderId: '946141681323',
    projectId: 'flutterfirebasetemplatesapps',
    storageBucket: 'flutterfirebasetemplatesapps.appspot.com',
    iosClientId: '946141681323-m67uo28uma79hujrujgbjdft72dkb7ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );
}
